version: '3.8'

services:
  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: family_tree
    ports:
      - 5438:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
  redis:
    image: "redislabs/redisgraph"
  api:
    build: .
    ports:
      - 3333:3333
    environment:
      - PORT=3333
      - DATABASE_URL=pg
      - APP_DB_USERNAME=postgres
      - APP_DB_PASSWORD=postgres
      - APP_DB_NAME=family_tree
    depends_on:
      - pg
      - redis

volumes:
  pg-data:
