version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
  redis:
    image: "redislabs/redisgraph"
  api:
    build: .
    ports:
      - 3333:3333
    environment:
      - PORT=3333
      - DATABASE_URL=db
    depends_on:
      - db
      - redis
